services:
  ollama:
    profiles: ["llm", "obsidian"]
    image: ollama/ollama:latest
    pull_policy: always
    container_name: ollama
    volumes:
      - ./mount/ollama:/root/.ollama
      - ./entrypoint.sh:/entrypoint.sh
    ports: ["11434:11434"]
    tty: true
    networks:
      - ollama-docker
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all 
              capabilities: [gpu]
    entrypoint: ["/usr/bin/bash", "/entrypoint.sh"]

  chromadb:
    profiles: ["obsidian", "chroma"]
    image: chromadb/chroma
    pull_policy: always
    container_name: chroma
    volumes:
      - ./mount/chromadb:/chromadb
    ports: ["8000:8000"]
    tty: true
    networks:
      - ollama-docker

  md-rag:
    profiles: ["obsidian"]
    build:
      context: /home/atsaryonau/projects/local-chatbot/md-rag
      dockerfile: Dockerfile
    container_name: md-rag
    environment:
      - OLLAMA_MODEL=llama3.2:3b
      - OLLAMA_EMBED_MODEL=mxbai-embed-large
      - OLLAMA_MODEL_TEMPERATURE=0.5
      - OLLAMA_HOST=http://ollama:11434
      - CHROMA_HOST=http://chroma:8000
      - MD_REPO=/app/md-repo
    volumes:
      - ./mount/md:/app/md-repo:ro
    networks:
      - ollama-docker
    depends_on:
      - chromadb
      - ollama

networks:
  ollama-docker:
    external: false
