services:
  ollama:
    profiles: ["llm", "obsidian", "gradio"]
    image: ollama/ollama:latest
    container_name: ollama
    environment:
      - OLLAMA_DEBUG=0
    volumes:
      - ./mount/ollama:/root/.ollama
      - ./entrypoint.sh:/entrypoint.sh
    ports: ["11434:11434"]
    tty: true
    networks:
      - ollama-docker
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all 
              capabilities: [gpu]
    entrypoint: ["/usr/bin/bash", "/entrypoint.sh"]

  chromadb:
    profiles: ["obsidian", "chroma", "gradio"]
    image: chromadb/chroma
    container_name: chroma
    volumes:
      - ./mount/chromadb:/chromadb
    ports: ["8000:8000"]
    tty: true
    networks:
      - ollama-docker

  md-ingestor:
    profiles: ["obsidian"]
    build:
      context: /home/atsaryonau/projects/local-chatbot/md-ingestor
      dockerfile: Dockerfile
    container_name: md-ingestor
    environment:
      - OLLAMA_MODEL=llama3.2:3b
      - OLLAMA_EMBED_MODEL=mxbai-embed-large
      - OLLAMA_MODEL_TEMPERATURE=0.5
      - OLLAMA_HOST=http://ollama:11434
      - CHROMA_HOST=http://chroma:8000
      - MD_REPO=/app/md
    volumes:
      - ./mount/md:/app/md:ro
    networks:
      - ollama-docker
    depends_on:
      - chromadb
      - ollama

  gradio-ui:
    profiles: ["obsidian", "gradio"]
    build:
      context: /home/atsaryonau/projects/local-chatbot/chat-ui
      dockerfile: Dockerfile
    container_name: gradio
    environment:
      - CHROMA_HOST=http://chroma:8000
      - OLLAMA_HOST=http://ollama:11434
      - OLLAMA_MODEL=llama3.2:3b
      - OLLAMA_EMBED_MODEL=mxbai-embed-large
    ports: ["7860:7860"]
    networks:
      - ollama-docker
    depends_on:
      - chromadb
      - ollama

networks:
  ollama-docker:
    external: false
