[project]
name = "chat-ui"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "chromadb>=1.3.7",
    "gradio>=6.1.0",
    "ollama>=0.6.1",
]
